# NumPy Data Types

## Numpy 's main data type is ndarray- which means the the arry can have many dimension

 # Declaring an array
 

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3]) #one dimensional array

In [3]:
type(array1)

numpy.ndarray

In [4]:
array2 = np.array([[1,2,3,4],
                 [2,3,4,5]])

In [5]:
import pandas as pd

In [6]:
dataFrame = pd.DataFrame(array2) #creating a dataframe from the array

In [7]:
dataFrame

0  1  2  3
0  1  2  3  4
1  2  3  4  5

In [8]:
type(dataFrame)

pandas.core.frame.DataFrame

In [9]:
newColumnNamea = ['A','B','C','D'] #changing the dataframe column names to A B C D

In [10]:
dataFrame.columns = newColumnNamea # assigning the columns name

In [11]:
dataFrame

A  B  C  D
0  1  2  3  4
1  2  3  4  5

In [12]:
newRowsNames = ['X','Y']

In [13]:
dataFrame.index = newRowsNames #changing the rows name , but in numpy we don't have row attributes so we have to use the index attribute

In [14]:
dataFrame

A  B  C  D
X  1  2  3  4
Y  2  3  4  5

In [15]:
#creating arrays automatically with numpy


onesArray = np.ones((2,3))

In [16]:
onesArray

array([[1., 1., 1.],
       [1., 1., 1.]])

# Generating Random Numbers using NumPy

In [17]:
randomArray = np.random.randint(6, size=(5,5))

In [18]:
randomArray

array([[3, 1, 2, 2, 0],
       [2, 0, 2, 1, 5],
       [3, 3, 4, 4, 3],
       [2, 2, 4, 5, 2],
       [0, 1, 4, 1, 3]])

## Suppose we need to share our notebook with someone else and we want to generate the same random numbers without changing anything in that case we can use  seed() function available on numpy


In [19]:
np.random.seed(seed = 0)
randomArrayConstantNumbers = np.random.randint(5, size=(4,5))
randomArrayConstantNumbers

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0],
       [1, 1, 0, 1, 4]])

# Viewing Arrays and  matrices

In [20]:
randomArray

array([[3, 1, 2, 2, 0],
       [2, 0, 2, 1, 5],
       [3, 3, 4, 4, 3],
       [2, 2, 4, 5, 2],
       [0, 1, 4, 1, 3]])

In [21]:
np.unique(randomArray)

array([0, 1, 2, 3, 4, 5])

In [22]:
array1

array([1, 2, 3])

In [23]:
array2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [25]:
array3 = np.array([[1,5,6,7,],
                 [5,7,2,5],
                 [5,5,26,8]])

In [26]:
array3

array([[ 1,  5,  6,  7],
       [ 5,  7,  2,  5],
       [ 5,  5, 26,  8]])

In [27]:
array1[0]

1

In [28]:
array2.shape


(2, 4)

In [29]:
array3.shape

(3, 4)

# Manipulating and Comparing Arrays

## Arithmetic 

In [30]:
array1

array([1, 2, 3])

In [31]:
array2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [32]:
array3

array([[ 1,  5,  6,  7],
       [ 5,  7,  2,  5],
       [ 5,  5, 26,  8]])

In [33]:
array4 = np.ones(3)

In [34]:
array4

array([1., 1., 1.])

In [35]:
sumOfTwo = array1 + array4

In [36]:
sumOfTwo

array([2., 3., 4.])

In [40]:
subsOfTwo = array1 - array4

In [41]:
subsOfTwo

array([0., 1., 2.])

In [42]:
multiplicationOfTwo = array1 * array4

In [43]:
multiplicationOfTwo

array([1., 2., 3.])

In [45]:
array2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [46]:
multiplication2 = array1 * array2 #this will not work since the columns of two arrays / matrices does not match

ValueError: operands could not be broadcast together with shapes (3,) (2,4) 

Broadcasting in Numpy describes how numpy treats arrays while performing arithmatic operations

https://numpy.org/doc/stable/user/basics.broadcasting.html

In [47]:
array5 = np.array([[2,3,4],
                  [4,5,6]])

In [48]:
array5

array([[2, 3, 4],
       [4, 5, 6]])

In [49]:
multiplication3 = array1 * array5

In [50]:
multiplication3

array([[ 2,  6, 12],
       [ 4, 10, 18]])

# Division and Floor Division

In [51]:
# division

division = array1/array4

In [52]:
division

array([1., 2., 3.])

In [53]:
#floor division

floorDivison = array1 // array4 

In [54]:
floorDivison #removes the decimal, it rounds up

array([1., 2., 3.])

In [55]:
x= 5
y =2


In [59]:
floorDiv1 = x/y

In [60]:
floorDiv1

2.0

In [61]:
# power

powerOfArray = array1 *array4

In [62]:
powerOfArray

array([1., 2., 3.])

Numpy has this arithmtic operations as functions 

Like for example

the square of the arrays we can use as 



In [63]:
np.square(array1 , array4) # this exactly does the same thing as {array1 * array4}

array([1., 4., 9.])

# Standard Deviation

https://www.mathsisfun.com/data/standard-deviation.html

# Aggregation


Performing the same operations on number of things

numpy has their own function of doing things, it has functions like sum , square etc etc, 

but where to use this is the factor 

Use Numpy function dealing with numpy arrays and use python functions for python datatypes

In [68]:
 #creating an massive array
    
massiveArray = np.random.random(100000)

In [71]:
massiveArray[:100]

array([0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834,
       0.79915856, 0.46147936, 0.78052918, 0.11827443, 0.63992102,
       0.14335329, 0.94466892, 0.52184832, 0.41466194, 0.26455561,
       0.77423369, 0.45615033, 0.56843395, 0.0187898 , 0.6176355 ,
       0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ,
       0.43703195, 0.6976312 , 0.06022547, 0.66676672, 0.67063787,
       0.21038256, 0.1289263 , 0.31542835, 0.36371077, 0.57019677,
       0.43860151, 0.98837384, 0.10204481, 0.20887676, 0.16130952,
       0.65310833, 0.2532916 , 0.46631077, 0.24442559, 0.15896958,
       0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
       0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947,
       0.4686512 , 0.97676109, 0.60484552, 0.73926358, 0.03918779,
       0.28280696, 0.12019656, 0.2961402 , 0.11872772, 0.31798318,
       0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
       0.52324805, 0.09394051, 0.5759465 , 0.9292962 , 0.31856

In [72]:
massiveArray[:10]

array([0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834,
       0.79915856, 0.46147936, 0.78052918, 0.11827443, 0.63992102])


## The %timeit magic command is used in IPython environments (like Jupyter notebooks or IPython interactive shells) to measure the execution time of a Python statement or expression. It provides a convenient way to quickly assess the performance of code snippets.

In [73]:
%timeit sum(massiveArray) #python sum function
%timeit np.sum(massiveArray) #numpy sum functions

6.41 ms ± 101 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.5 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


numpy functions takes less time than the python default functions

beacuse numpy is optimised to do more mathematical calulations on a faster rate

In [75]:
meanOfArray = np.mean(array1)

In [76]:
meanOfArray

2.0

In [79]:
array5

array([[2, 3, 4],
       [4, 5, 6]])

In [77]:
meanOfArray5 = np.mean(array5)

In [78]:
meanOfArray5

4.0

In [81]:
maxOfArray = np.max(array4)
maxOfArray

1.0

In [83]:
minOfArray = np.min(array5)
minOfArray

2

In [85]:
standardDeviationOfArray = np.std(array4) #standard deviation
standardDeviationOfArray

3.2998316455372216

In [91]:
#standard deviaiton = squareroot of the variance

basicFormulaOfStd = np.sqrt(np.var(array4))
basicFormulaOfStd


3.2998316455372216

In [89]:
varianceOfArray = np.var(array5) #variance
varianceOfArray

1.6666666666666667