# NumPy Data Types

## Numpy 's main data type is ndarray- which means the the arry can have many dimension

 # Declaring an array
 

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3]) #one dimensional array

In [3]:
type(array1)

numpy.ndarray

In [4]:
array2 = np.array([[1,2,3,4],
                 [2,3,4,5]])

In [5]:
import pandas as pd

In [6]:
dataFrame = pd.DataFrame(array2) #creating a dataframe from the array

In [7]:
dataFrame

0  1  2  3
0  1  2  3  4
1  2  3  4  5

In [8]:
type(dataFrame)

pandas.core.frame.DataFrame

In [9]:
newColumnNamea = ['A','B','C','D'] #changing the dataframe column names to A B C D

In [10]:
dataFrame.columns = newColumnNamea # assigning the columns name

In [11]:
dataFrame

A  B  C  D
0  1  2  3  4
1  2  3  4  5

In [12]:
newRowsNames = ['X','Y']

In [13]:
dataFrame.index = newRowsNames #changing the rows name , but in numpy we don't have row attributes so we have to use the index attribute

In [14]:
dataFrame

A  B  C  D
X  1  2  3  4
Y  2  3  4  5

In [15]:
#creating arrays automatically with numpy


onesArray = np.ones((2,3))

In [16]:
onesArray

array([[1., 1., 1.],
       [1., 1., 1.]])

# Generating Random Numbers using NumPy

In [17]:
randomArray = np.random.randint(6, size=(5,5))

In [18]:
randomArray

array([[3, 1, 2, 2, 0],
       [2, 0, 2, 1, 5],
       [3, 3, 4, 4, 3],
       [2, 2, 4, 5, 2],
       [0, 1, 4, 1, 3]])

## Suppose we need to share our notebook with someone else and we want to generate the same random numbers without changing anything in that case we can use  seed() function available on numpy


In [19]:
np.random.seed(seed = 0)
randomArrayConstantNumbers = np.random.randint(5, size=(4,5))
randomArrayConstantNumbers

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0],
       [1, 1, 0, 1, 4]])

# Viewing Arrays and  matrices

In [20]:
randomArray

array([[3, 1, 2, 2, 0],
       [2, 0, 2, 1, 5],
       [3, 3, 4, 4, 3],
       [2, 2, 4, 5, 2],
       [0, 1, 4, 1, 3]])

In [21]:
np.unique(randomArray)

array([0, 1, 2, 3, 4, 5])

In [22]:
array1

array([1, 2, 3])

In [23]:
array2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [25]:
array3 = np.array([[1,5,6,7,],
                 [5,7,2,5],
                 [5,5,26,8]])

In [26]:
array3

array([[ 1,  5,  6,  7],
       [ 5,  7,  2,  5],
       [ 5,  5, 26,  8]])

In [27]:
array1[0]

1

In [28]:
array2.shape


(2, 4)

In [29]:
array3.shape

(3, 4)

# Manipulating and Comparing Arrays

## Arithmetic 

In [30]:
array1

array([1, 2, 3])

In [31]:
array2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [32]:
array3

array([[ 1,  5,  6,  7],
       [ 5,  7,  2,  5],
       [ 5,  5, 26,  8]])

In [33]:
array4 = np.ones(3)

In [34]:
array4

array([1., 1., 1.])

In [35]:
sumOfTwo = array1 + array4

In [36]:
sumOfTwo

array([2., 3., 4.])

In [40]:
subsOfTwo = array1 - array4

In [41]:
subsOfTwo

array([0., 1., 2.])

In [42]:
multiplicationOfTwo = array1 * array4

In [43]:
multiplicationOfTwo

array([1., 2., 3.])

In [45]:
array2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [46]:
multiplication2 = array1 * array2 #this will not work since the columns of two arrays / matrices does not match

ValueError: operands could not be broadcast together with shapes (3,) (2,4) 

Broadcasting in Numpy describes how numpy treats arrays while performing arithmatic operations

In [47]:
array5 = np.array([[2,3,4],
                  [4,5,6]])

In [48]:
array5

array([[2, 3, 4],
       [4, 5, 6]])

In [49]:
multiplication3 = array1 * array5

In [50]:
multiplication3

array([[ 2,  6, 12],
       [ 4, 10, 18]])